#-----Service Exception----
UserRepository.REGISTRATION_SUCCESS="You have successfully booked movie with movie id";
RegistrationService.INVALID_USERNAME= "Invalid username!";
RegistrationService.INVALID_EMAIL= "Invalid email id !";
RegistrationService.INVALID_PHONENUMBER="Invalid phonenumber !";
RegistrationService.INVALID_CITY="Invalid city!";